version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/long_term_memory:/qdrant/storage
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/short_term_memory:/app/data
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - qdrant
